apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: l7services.kindmesh.io
spec:
  group: kindmesh.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                selector:
                  type: object
                  additionalProperties:
                    type: string
                protocol:
                  type: string
                targetPort:
                  type: integer
                routes:
                  type: array
                  items:
                    type: object
                    properties:
                      match:
                        type: object
                        properties:
                          prefix:
                            type: string
                          path:
                            type: string
                          regex:
                            type: string
                          headers:
                            type: array
                            items:
                              type: object
                              properties:
                                name:
                                  type: string
                                exact_match:
                                  type: string
                                regex_match:
                                  type: string
                          query_parameters:
                            type: array
                            items:
                              type: object
                              properties:
                                name:
                                  type: string
                                value:
                                  type: string
                                match_type:
                                  type: string
                                  enum: ["exact", "prefix", "suffix", "regex", "contains"]
                                ignore_case:
                                  type: boolean
                      router:
                        type: object
                        properties:
                          subset:
                            type: string
                          prefix_rewrite:
                            type: string

  scope: Namespaced
  names:
    plural: l7services
    singular: l7service
    kind: L7Service
    shortNames:
    - l7svc