admin:
  access_log_path: /dev/null
  address:
    socket_address:
      address: 169.254.99.2
      port_value: 19000
dynamic_resources:
  cds_config:
    resource_api_version: V3
    api_config_source:
      api_type: GRPC
      transport_api_version: V3
      grpc_services:
      - envoy_grpc:
          cluster_name: kind_xds_cluster
      set_node_on_first_message_only: true
  lds_config:
    resource_api_version: V3
    api_config_source:
      api_type: GRPC
      transport_api_version: V3
      grpc_services:
      - envoy_grpc:
          cluster_name: kind_xds_cluster
      set_node_on_first_message_only: true
node:
  cluster: local-cluster
  id: nodeID
static_resources:
  clusters:
  - connect_timeout: 1s
    load_assignment:
      cluster_name: kind_xds_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 169.254.99.2
                port_value: 80
    http2_protocol_options: {}
    name: kind_xds_cluster

layered_runtime:
  layers:
    - name: runtime-0
      rtds_layer:
        rtds_config:
          resource_api_version: V3
          api_config_source:
            transport_api_version: V3
            api_type: GRPC
            grpc_services:
              envoy_grpc:
                cluster_name: kind_xds_cluster
        name: runtime-0